Chore(docs) : Add contribution guidelines
auvzhcet/Documentation pull request #29
Opened 2020-07-05 19:22 UTC by salonigupta1

2020-07-05 19:46 UTC, pnijhara requested changes

2020-07-05 19:46 UTC, pnijhara commented on contribution.md
> +#### When contributing to this project, please first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change.
This should be a normal text and not a h4.

2020-07-05 19:46 UTC, pnijhara commented on contribution.md
> +#### Please note we have a code of conduct, please follow it in all your interactions with the project.
Normal text.

2020-07-05 19:46 UTC, pnijhara commented on contribution.md
> +#### 1.Ensure any install or build dependencies are removed before the end of the layer when doing a build.
Normal point

2020-07-05 19:46 UTC, pnijhara commented on contribution.md
> +#### 2.Update the README.md with details of changes to the interface, this includes new environment variables, exposed ports, useful file locations and container parameters.
Again this should be a normal text point.

2020-07-05 19:46 UTC, pnijhara commented on contribution.md
> +#### [References](https://www.conventionalcommits.org/en/v1.0.0/)
Normal link.

2020-07-05 19:49 UTC, pnijhara commented
@salonigupta1 you have written most of the content in h3 and h4. I recommend you to please go through the content and again and use the normal text wherever required. Also, make a directory named Development and add `contributing.md` and other files related to development process into this.

@syedjawadakhtar can you look into this, please?

2020-07-06 00:26 UTC, syedjawadakhtar commented
- I guess @salonigupta1 is trying to make all the texts bold and bigger by putting it under h4. 
- Use headings only when there is a change in context. You may number the headings as 1. 2. 3. to reduce any complexity in the article. Similarly, for subheadings, use 1.1, 2.1 ...
- Follow the hierarchy for headings as well. h1 -> h2 -> h3 -> h4 for pretty printing.
- You can get a go-to guide for *markdown* here in this tutorial:
[https://github.com/luong-komorebi/Markdown-Tutorial](https://github.com/luong-komorebi/Markdown-Tutorial)

2020-07-06 18:26 UTC, pnijhara requested changes

2020-07-06 18:26 UTC, pnijhara commented on Development/CONTRIBUTING.md
> +# CONTRIBUTING GUIDLINES
This file should come under docs directory.
docs/Develoment/CONTRIBUTING.md

2020-07-06 18:26 UTC, pnijhara commented on contribution.md
> +#### When contributing to this project, please first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change.
Remove this file!

2020-07-06 18:26 UTC, pnijhara commented on docs/CONTRIBUTING.md
> +
Remove this file also!

2020-07-06 18:28 UTC, pnijhara commented
@salonigupta1 there are still changes required.
Since you have added a new subdirectory named Development. You can add this directory within docs directory and update nav link in mkdocs.yml file.

2020-07-06 18:51 UTC, pnijhara commented
I am merging this PR. Will update the changes on my own!
Thank you for the contribution @salonigupta1

2020-07-06 18:51 UTC, merged