doc: Add a how to guide for making new/existing repository in AUV ZHCET Organization
auvzhcet/Documentation pull request #49
Opened 2020-07-08 11:35 UTC by Zaidtech

# Checklist

- [x] Closes #25
- [ ] Passes `Semantic Pull Request` and `TypoCheck`
- [x] New functions/methods are listed in `README.md`
- [x] New functions/methods are listed in `index.md`
- [  ] Updated table of content
- [x] Updated nav links in mkdocs.yml

---

## PR description
Solves issue #25 -how to start making a repository guide.

2020-07-08 11:55 UTC, pnijhara requested changes

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +# GIT REPOSITORY HOW-TO GUIDE
Remove the empty space after end of line.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +### git init/ git clone
Leave an empty line after line1

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +[How to set-up Git on your device](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup)
Leave a line after the heading.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +To create a new repo, you'll use the **git init** command. git init is a one-time command you use during the initial setup of a new repo. Executing this command will create a new **.git**   subdirect
Headings should be surrounded by blank lines.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +If a project has been set up in a central repository, the **clone** command is the most common way to obtain a local development clone.Once a developer(contributor) has obtained a working copy, all v
Headings should be surrounded by blank lines.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +To create a new repo, you'll use the **git init** command. git init is a one-time command you use during the initial setup of a new repo. Executing this command will create a new **.git**   subdirect
Remove empty space after the end of line.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +* execute **git init**
Remove empty space.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +    git clone <repo url>
No need to add indentation.
This should be "a code block".

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> + git clone creates a local clone of remote repo.
Remove empty space.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> + The URL can be found on this page under **CODE** dropdown can be found [on this page.](https://github.com/auvzhcet/Documentation)
Remove empty space before starting of the line.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> + ### Saving changes to the repo
Headings should be surrounded by blank lines.

2020-07-08 11:55 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +**git push**
Headings should be surrounded by blank lines.

2020-07-08 11:57 UTC, pnijhara commented
@Zaidtech There are lining issues in this patch. I have suggested some. If you are using VScode I suggest you install markdown linter extension in your code editor.

2020-07-08 13:18 UTC, Zaidtech commented
@pnijhara I have resolved the issue, kindly check them.

2020-07-08 15:57 UTC, pnijhara requested changes

2020-07-08 15:57 UTC, pnijhara commented on .idea/.gitignore
> +# Default ignored files
Remove these files.

2020-07-08 15:57 UTC, pnijhara commented on .idea/Documentation.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file.

2020-07-08 15:57 UTC, pnijhara commented on .idea/Documentation.iml
> +  <component name="NewModuleRootManager">
Remove this file.

2020-07-08 15:57 UTC, pnijhara commented on .idea/inspectionProfiles/profiles_settings.xml
> +    <option name="USE_PROJECT_PROFILE" value="false" />
Remove this file.

2020-07-08 15:57 UTC, pnijhara commented on .idea/misc.xml
> +  <component name="JavaScriptSettings">
Remove this file.

2020-07-08 15:57 UTC, pnijhara commented on .idea/modules.xml
> +<project version="4">
Remove this file.

2020-07-08 15:57 UTC, pnijhara commented on .idea/vcs.xml
> +<project version="4">
Remove this file.

2020-07-08 15:58 UTC, pnijhara commented on docs/Development/Creating_a_Repository_guide.md
> +To create a new repo, you'll use the **git init** command. git init is a one-time command you use during the initial setup of a new repo. Executing this command will create a new **.git**   subdirect
Add a line after heading.

2020-07-09 05:26 UTC, Zaidtech commented
Removed the .idea files. @pnijhara, please check the same.

2020-07-09 07:07 UTC, pnijhara approved these changes

2020-07-09 07:46 UTC, syedjawadakhtar requested changes
This article must be more focused on the format of the title of the repository, what to write in README, and how to properly document so that the code could be replicated by anyone.
Following the basic structure from here: [Launching your own open-source project - opensource.guide](https://opensource.guide/starting-a-project/#launching-your-own-open-source-project) - providing the sample files to each one of these.

These git commands can be added in a subsection as "Git Command Guide".

2020-07-09 07:46 UTC, syedjawadakhtar commented on docs/Development/Creating_a_Repository_guide.md
> +To create a new repo, you'll use the **git init** command. git init is a one-time command you use during the initial setup of a new repo. Executing this command will create a new **.git**   subdirect
When using terminal commands in content, better show it between three back quotes (`)
Like this:
```zsh
git init
```

2020-07-09 07:51 UTC, pnijhara commented
For starting I think this much content is fine. We will update this with time. I am merging this one for now.

2020-07-09 07:58 UTC, pnijhara approved these changes

2020-07-09 07:58 UTC, merged

2020-07-09 08:00 UTC, pnijhara commented
Thank you for the contribution @Zaidtech