docs: Student report (computer)
auvzhcet/Documentation pull request #71
Opened 2020-07-15 07:29 UTC by TamkeenFatima

# Checklist

- [ ] fixes #xxxx
- [ ] Passes `Semantic Pull Request` and `TypoCheck`
- [ ] New docs are listed in `README.md`
- [ ] New docs are listed in `index.md`
- [ ] Updated table of content
- [ ] Updated nav links in mkdocs.yml

---

## PR description

Add Tamkeen's report
Update computer's `students.md`

2020-07-15 07:32 UTC, pnijhara requested changes

2020-07-15 07:32 UTC, pnijhara commented on docs/computer/student_Reports/Tamkeen_2019-20.md
> +### 1.7 Refrences
typo

2020-07-15 19:19 UTC, pnijhara commented
Could you please write stuff in 3rd person?

2020-07-15 19:23 UTC, syedjawadakhtar requested changes

2020-07-15 19:23 UTC, syedjawadakhtar commented on docs/computer/student_Reports/Tamkeen_2019-20.md
> +- Afzal, Afsoon & Katz, Deborah & Goues, Claire & Timperley, Christopher. (2020). A Study on the Challenges of Using Robotics Simulators for Testing.
A link to references would be better.

2020-07-20 16:09 UTC, pnijhara commented
Are you on it @TamkeenFatima?

2020-08-06 19:34 UTC, pnijhara commented
ping @TamkeenFatima !

2020-08-23 10:14 UTC, pnijhara approved these changes

2020-08-23 10:15 UTC, merged